docs: revise Arch Linux Dependencies installation
error: target not found: android-sdk-build-tools
pacman does not have android-sdk-build-tools, so use yay instead to fetch from AUR.